services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - pnpm-cache:/root/.local/share/pnpm/store
      - cargo-cache:/usr/local/cargo/registry
      - target-cache:/app/src-tauri/target
    ports:
      - "1420:1420"
    tty: true
    stdin_open: true
    environment:
      - DISPLAY=${DISPLAY} # X11/Wayland 転送用（Linux/WSL2/XServer等が必要）

volumes:
  pnpm-cache:
  cargo-cache:
  target-cache:
